import AuthenticationServices
import CryptoKit
import FirebaseAuth
import FirebaseCore
import Foundation
import Security
import UIKit

@MainActor
enum FirebaseAuthSession {
    static var isConfigured: Bool {
        FirebaseApp.app() != nil
    }

    static var hasCurrentUser: Bool {
        isConfigured && Auth.auth().currentUser != nil
    }

    static var isAnonymous: Bool {
        isConfigured && Auth.auth().currentUser?.isAnonymous == true
    }

    static func ensureCurrentUser() async throws -> String {
        if let uid = Auth.auth().currentUser?.uid {
            return uid
        }
        do {
            return try await Auth.auth().signInAnonymously().user.uid
        } catch {
            throw FirebaseRepositoryError.map(error)
        }
    }

    /// Deletion is followed by an explicit "Start fresh" action. Never let that
    /// path reuse a stale Firebase user left in memory while the prior sign-out is
    /// settling: sign out first, create a new anonymous identity, then force an
    /// ID-token round trip before Firestore creates the replacement profile.
    static func startFreshAnonymousUser() async throws -> String {
        do {
            if Auth.auth().currentUser != nil {
                try Auth.auth().signOut()
            }
            let user = try await Auth.auth().signInAnonymously().user
            _ = try await user.getIDTokenResult(forcingRefresh: true)
            return user.uid
        } catch {
            throw FirebaseRepositoryError.map(error)
        }
    }

    /// Links Apple to the existing anonymous Firebase user, preserving the UID that
    /// already owns posts, Storage paths, outbox rows, friendships, and RevenueCat.
    /// If a non-anonymous user is present, no account replacement is performed.
    static func linkCurrentAnonymousUserWithApple() async throws -> String {
        guard let user = Auth.auth().currentUser else { throw RepositoryError.notAuthenticated }
        guard user.isAnonymous else { return user.uid }

        let priorUID = user.uid
        let appleAuthorization = try await AppleAuthorizationCoordinator.authorize()
        let credential = try firebaseCredential(
            from: appleAuthorization.credential,
            rawNonce: appleAuthorization.rawNonce
        )
        do {
            let result = try await user.link(with: credential)
            guard result.user.uid == priorUID else {
                throw AppleAccountLinkError.identityChanged
            }
            return result.user.uid
        } catch let error as AppleAccountLinkError {
            throw error
        } catch {
            throw AppleAccountLinkError.map(error)
        }
    }

    /// Used before an anonymous account exists, for example after reinstalling the
    /// app. Apple/Firebase returns the previously linked Firebase UID, which keeps
    /// the RevenueCat App User ID stable across devices without a receipt transfer.
    static func signInWithApple() async throws -> String {
        let appleAuthorization = try await AppleAuthorizationCoordinator.authorize()
        return try await signInWithApple(
            credential: appleAuthorization.credential,
            rawNonce: appleAuthorization.rawNonce
        )
    }

    /// Completes the Firebase half of the authorization generated by
    /// `SignInWithAppleButton`. Keeping the nonce with that UI request prevents
    /// a second Apple sheet and binds Firebase's credential to the same request.
    static func signInWithApple(
        credential appleCredential: ASAuthorizationAppleIDCredential,
        rawNonce: String
    ) async throws -> String {
        let credential = try firebaseCredential(from: appleCredential, rawNonce: rawNonce)
        do {
            return try await Auth.auth().signIn(with: credential).user.uid
        } catch {
            throw AppleAccountLinkError.map(error)
        }
    }

    private static func firebaseCredential(
        from credential: ASAuthorizationAppleIDCredential,
        rawNonce: String
    ) throws -> AuthCredential {
        guard let tokenData = credential.identityToken,
              let token = String(data: tokenData, encoding: .utf8)
        else { throw AppleAccountLinkError.invalidCredential }
        // Use Firebase's Apple-specific constructor so the one-time full name is
        // retained on the first authorization. The generic OAuth constructor has
        // a typed provider identifier in current FirebaseAuth and loses that data.
        return OAuthProvider.appleCredential(
            withIDToken: token,
            rawNonce: rawNonce,
            fullName: credential.fullName
        )
    }
}

enum AppleAccountLinkError: LocalizedError {
    case invalidCredential
    case credentialAlreadyLinked
    case identityChanged
    case cancelled
    case failed

    static func map(_ error: Error) -> Self {
        let nsError = error as NSError
        if nsError.domain == ASAuthorizationError.errorDomain,
           nsError.code == ASAuthorizationError.canceled.rawValue {
            return .cancelled
        }
        if nsError.domain == AuthErrorDomain,
           nsError.code == AuthErrorCode.credentialAlreadyInUse.rawValue {
            return .credentialAlreadyLinked
        }
        return .failed
    }

    var errorDescription: String? {
        switch self {
        case .invalidCredential:
            "Apple could not verify this sign-in. Please try again."
        case .credentialAlreadyLinked:
            "This Apple Account belongs to another Sky Grid account. Its photos were not merged."
        case .identityChanged:
            "Sky Grid could not preserve this account identity."
        case .cancelled:
            ""
        case .failed:
            "Apple sign-in could not be completed. Please try again."
        }
    }
}

enum AppleSignInNonce {
    static func make() -> String {
        let characters = Array("0123456789ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvwxyz-._")
        var result = ""
        var remaining = 32
        while remaining > 0 {
            var random: UInt8 = 0
            let status = SecRandomCopyBytes(kSecRandomDefault, 1, &random)
            guard status == errSecSuccess else { continue }
            if Int(random) < characters.count {
                result.append(characters[Int(random)])
                remaining -= 1
            }
        }
        return result
    }

    static func sha256(_ value: String) -> String {
        SHA256.hash(data: Data(value.utf8)).map { String(format: "%02x", $0) }.joined()
    }
}

@MainActor
private final class AppleAuthorizationCoordinator: NSObject, ASAuthorizationControllerDelegate, ASAuthorizationControllerPresentationContextProviding {
    private var continuation: CheckedContinuation<ASAuthorizationAppleIDCredential, Error>?

    static func authorize() async throws -> AppleAuthorization {
        let coordinator = AppleAuthorizationCoordinator()
        let nonce = AppleSignInNonce.make()
        let credential = try await coordinator.performAuthorization(nonce: nonce)
        return AppleAuthorization(credential: credential, rawNonce: nonce)
    }

    private func performAuthorization(nonce: String) async throws -> ASAuthorizationAppleIDCredential {
        try await withCheckedThrowingContinuation { continuation in
            self.continuation = continuation
            let request = ASAuthorizationAppleIDProvider().createRequest()
            request.requestedScopes = [.email]
            request.nonce = AppleSignInNonce.sha256(nonce)
            let controller = ASAuthorizationController(authorizationRequests: [request])
            controller.delegate = self
            controller.presentationContextProvider = self
            controller.performRequests()
        }
    }

    func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization) {
        guard let credential = authorization.credential as? ASAuthorizationAppleIDCredential else {
            continuation?.resume(throwing: AppleAccountLinkError.invalidCredential)
            continuation = nil
            return
        }
        continuation?.resume(returning: credential)
        continuation = nil
    }

    func authorizationController(controller: ASAuthorizationController, didCompleteWithError error: Error) {
        continuation?.resume(throwing: AppleAccountLinkError.map(error))
        continuation = nil
    }

    func presentationAnchor(for controller: ASAuthorizationController) -> ASPresentationAnchor {
        UIApplication.shared.connectedScenes
            .compactMap { $0 as? UIWindowScene }
            .flatMap(\.windows)
            .first(where: \.isKeyWindow) ?? ASPresentationAnchor()
    }

}

private struct AppleAuthorization {
    let credential: ASAuthorizationAppleIDCredential
    let rawNonce: String
}
